import { useState } from 'react'
import { Mail, FileText, Copy, Check, ChevronDown, ChevronUp, Send, Building2, Globe, Leaf, Plane, Cpu, DollarSign, MapPin, Briefcase } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { cn } from '@/lib/cn'

interface Template { id: string; title: string; type: 'email' | 'proposal' | 'one-pager' | 'follow-up'; sector?: string; content: string; variables?: string[] }

const TEMPLATES: Template[] = [
  { id: 'email-cold-investor', title: 'Cold Outreach — Investor/Family Office', type: 'email', content: 'Subject: Strategic Facilitation Partnership — AarKi Trinetra Capital\n\nDear [INVESTOR_NAME],\n\nI hope this message finds you well. I\'m writing to introduce AarKi Trinetra Capital, a next-generation strategic facilitation firm operating across India\'s most dynamic sectors.\n\nWe specialize in connecting high-quality capital with precision-aligned opportunities in:\n• Real Estate & Strategic Assets\n• Renewable Energy & Green Infrastructure\n• Infrastructure & EPC Projects\n• Structured Capital & Exit Strategies\n\nOur model is strictly advisory and facilitation-based — we ensure complete compliance, risk insulation, and scalable deal structuring.\n\nI believe there may be strong synergy between your investment thesis and our current pipeline of [SECTOR] opportunities in [LOCATION].\n\nWould you be open to a brief 20-minute call?\n\nWarm regards,\nAADI JOSHY\nFounder & Principal Strategic Facilitator\nAarKi Trinetra Capital\nCapital. Vision. Scale.', variables: ['INVESTOR_NAME', 'SECTOR', 'LOCATION'] },
  { id: 'email-cold-developer', title: 'Cold Outreach — Developer/Project Owner', type: 'email', content: 'Subject: Capital & Strategic Alignment Opportunity\n\nDear [DEVELOPER_NAME],\n\nI\'m reaching out from AarKi Trinetra Capital — a strategic facilitation firm that bridges project owners with the right capital and execution partners.\n\nWe understand [PROJECT_NAME] is at a critical stage, and we believe our network of [CAPITAL_TYPE] investors can add significant value.\n\nWhat we bring:\n• Precision capital matching\n• Access to HNI investors, family offices\n• End-to-end deal structuring\n• NCNDA-governed, compliance-first approach\n\nOur facilitation fee is success-based.\n\nBest regards,\nAADI JOSHY\nAarKi Trinetra Capital', variables: ['DEVELOPER_NAME', 'PROJECT_NAME', 'CAPITAL_TYPE'] },
  { id: 'email-follow-up', title: 'Follow-Up — Post Initial Contact', type: 'follow-up', content: 'Subject: Following Up — AarKi Trinetra Capital\n\nDear [NAME],\n\nThank you for your time on our recent call regarding [TOPIC].\n\nAs discussed, we\'ve identified [NUMBER] potential opportunities in [SECTOR]:\n1. [OPPORTUNITY_1]\n2. [OPPORTUNITY_2]\n3. [OPPORTUNITY_3]\n\nNext Steps:\n• Detailed profiles under NCNDA\n• Deeper dive with sector specialist\n• Preliminary alignment discussions\n\nPlease let me know your availability.\n\nWarm regards,\nAADI JOSHY\nAarKi Trinetra Capital', variables: ['NAME', 'TOPIC', 'NUMBER', 'SECTOR', 'OPPORTUNITY_1', 'OPPORTUNITY_2', 'OPPORTUNITY_3'] },
  { id: 'email-mou-send', title: 'MOU Dispatch — Engagement Initiation', type: 'email', content: 'Subject: MOU for Review — AarKi Trinetra Capital x [PARTNER_NAME]\n\nDear [PARTNER_NAME],\n\nAs discussed, please find attached our standard MOU governing our facilitation partnership.\n\nThis document outlines:\n• Scope of facilitation engagement\n• Roles and responsibilities\n• Confidentiality obligations\n• Terms and conditions\n\nOnce mutually signed, we will begin alignment activities for [PROJECT/SECTOR].\n\nBest regards,\nAADI JOSHY\nAarKi Trinetra Capital', variables: ['PARTNER_NAME', 'PROJECT/SECTOR'] },
  { id: 'email-intro-psu', title: 'Introduction — PSU/Government Coordination', type: 'email', content: 'Subject: Strategic Facilitation for [PROJECT_NAME]\n\nDear [OFFICIAL_NAME],\n\nAarKi Trinetra Capital is a India-based strategic facilitation firm specializing in large-scale infrastructure and energy projects.\n\nWe are reaching out to explore coordination opportunities for [PROJECT_NAME/SCHEME].\n\nOur capabilities:\n• Stakeholder identification and alignment\n• Investor and EPC partner matchmaking\n• DPR coordination and feasibility support\n• Cross-border partnership facilitation\n\nWe would be grateful for an opportunity to present our credentials.\n\nRespectfully,\nAADI JOSHY\nAarKi Trinetra Capital', variables: ['PROJECT_NAME', 'OFFICIAL_NAME'] },
  { id: 'proposal-re-facilitation', title: 'Real Estate Facilitation Proposal', type: 'proposal', sector: 'Real Estate & Strategic Assets', content: '# AarKi Trinetra Capital\n## Real Estate Facilitation Proposal\n\nPrepared for: [CLIENT_NAME]\nProject: [PROJECT_NAME]\n\n## 1. Executive Summary\nAarKi Trinetra Capital proposes to act as the Strategic Facilitation Partner, providing capital alignment, stakeholder coordination, and deal structuring advisory.\n\n## 2. Scope of Services\nPhase 1 (Weeks 1-2): Assessment & Structuring\n• Documentation review and valuation\n• Deal structuring advisory (JDA/Equity/Quasi-Equity)\n\nPhase 2 (Weeks 3-6): Capital & Partner Alignment\n• Investor profiling and matchmaking\n• Developer/EPC partner identification\n\nPhase 3 (Weeks 7-12): Execution Enablement\n• Multi-stakeholder coordination\n• Due diligence facilitation\n\n## 3. Our Advantage\n• Pan-India network: 500+ investors & developers\n• Sector expertise across RE, infra, energy\n• NCNDA-governed, compliance-first\n• Success-based fees — no upfront cost\n\n## 4. Engagement Terms\n• Facilitation Fee: Success-based\n• Duration: 90-120 days\n\n## 5. Next Steps\n1. Execute NCNDA\n2. Share project documentation\n3. Initiate Phase 1 assessment\n\nAarKi Trinetra Capital — Capital. Vision. Scale.', variables: ['CLIENT_NAME', 'PROJECT_NAME'] },
  { id: 'proposal-energy', title: 'Renewable Energy Facilitation Proposal', type: 'proposal', sector: 'Renewable Energy & Green Infrastructure', content: '# AarKi Trinetra Capital\n## Renewable Energy Facilitation Proposal\n\n## 1. Opportunity Overview\nIndia RE: $50B+ through 2030. [PROJECT_NAME] positioned in [SUB_SECTOR].\n\n## 2. Facilitation Scope\nSolar/Green Hydrogen:\n• Investor alignment (PE, Infrastructure Funds, DFI)\n• EPC partner matchmaking\n• Government/PSU coordination\n• Carbon credit advisory\n\nEV Infrastructure:\n• Charging network investor facilitation\n• OEM connections\n• Policy incentive navigation\n\n## 3. Capital Structuring\n• Equity: ₹50Cr - ₹500Cr\n• Green Bonds: ₹100Cr+\n• Project Finance: ₹20Cr - ₹200Cr\n• Venture: ₹5Cr - ₹50Cr\n\n## 4. Network\n• 200+ RE investors\n• 50+ EPC contractors\n• Government liaison across 15+ states\n• International DFI connections\n\nAarKi Trinetra Capital — Capital. Vision. Scale.', variables: ['CLIENT_NAME', 'PROJECT_NAME', 'SUB_SECTOR'] },
  { id: 'proposal-infra', title: 'Infrastructure & EPC Facilitation Proposal', type: 'proposal', sector: 'EPC & Infrastructure', content: '# AarKi Trinetra Capital\n## Infrastructure & EPC Facilitation Proposal\n\n## 1. Project Context\nIndia capex: ₹11+ lakh crore. [PROJECT_NAME] in [INFRA_SEGMENT].\n\n## 2. Facilitation Framework\nCapital Alignment:\n• Equity/quasi-equity for BOT/HAM\n• InvIT structuring\n• Pension/insurance fund mobilization\n\nStakeholder Matching:\n• EPC contractor identification\n• PMC partner facilitation\n• Technology and O&M connections\n\nRisk Mitigation:\n• VGF advisory\n• Revenue model optimization\n• Insurance facilitation\n\nAarKi Trinetra Capital — Capital. Vision. Scale.', variables: ['CLIENT_NAME', 'PROJECT_NAME', 'INFRA_SEGMENT'] },
  { id: 'one-pager-company', title: 'Company Overview — One-Pager', type: 'one-pager', content: '# AarKi Trinetra Capital\n## Capital. Vision. Scale.\n\n## Who We Are\nA next-generation strategic facilitation firm — connecting investors, developers, institutions through structured intelligence.\n\n## What We Do\nBridge Capital, Assets & Execution Partners across 8+ sectors:\n• Real Estate: JDA, Land Aggregation, Hotel Assets\n• Capital & Investment: Equity, HNI, Family Offices\n• Renewable Energy: Solar, Green Hydrogen, EV\n• Infrastructure: Roads, Highways, Smart Cities\n• DPR & Feasibility: Studies, ROI Modeling\n• Structured Finance: Project Finance, Syndicated Loans\n• Aviation: Airports, MRO, Cargo\n• Digital: Data Centers, IT Parks, ERP\n\n## How We Operate\n✅ Advisory & Facilitation — Zero Execution Risk\n✅ NCNDA-Governed\n✅ Success-Based Fees\n✅ Pan-India Operations\n✅ 100% Compliance-First\n\n## Philosophy\n1. Clarity of Structure\n2. Capital Alignment\n3. Execution Enablement\n\nContact: Aadi Joshy — Founder\nEmail: [EMAIL] | Phone: [PHONE]\nwww.aarkitrinetracapital.com', variables: ['EMAIL', 'PHONE'] },
  { id: 'one-pager-re', title: 'Real Estate Sector — One-Pager', type: 'one-pager', sector: 'Real Estate & Strategic Assets', content: '# AarKi Trinetra Capital\n## Real Estate & Strategic Assets\n\n## Market Opportunity\n• India RE: $450B+ (2026)\n• Tier-2: 40%+ YoY growth\n• Logistics: 350M sq ft demand\n• Hospitality RevPAR: +22%\n\n## Our Services\n🏠 Land Acquisition — Aggregation, due diligence\n📐 JDA Structuring — Joint Development facilitation\n🏨 Hotel Assets — Branded residences, transactions\n🌍 Pan-India — 300+ developer connections\n\n## Capital Alignment\n• Equity: ₹10Cr - ₹500Cr\n• HNI: ₹1Cr - ₹50Cr tickets\n• Family Offices: Long-term models\n• NRI: $18B annual flow\n\nContact: [EMAIL] | [PHONE]', variables: ['EMAIL', 'PHONE'] },
  { id: 'one-pager-energy', title: 'Renewable Energy — One-Pager', type: 'one-pager', sector: 'Renewable Energy & Green Infrastructure', content: '# AarKi Trinetra Capital\n## Renewable Energy & Green Infrastructure\n\n## Market\n• RE target: 500 GW by 2030\n• Solar: ₹2.14/kWh (record)\n• Green H2 Mission: ₹2.3 lakh Cr\n• EV: 50,000 stations by 2028\n\n## Services\n☀️ Solar — Park development, investor alignment\n💚 Green Hydrogen — Project structuring, PSU coordination\n⚡ EV — Charging network facilitation\n📋 Carbon Credits — Advisory and marketplace\n\n## Capital\n• Infra Funds: ₹50Cr - ₹500Cr\n• DFI: ADB, World Bank, AIIB\n• Green Bonds: Listed developers\n• VC: Clean-tech, H2 startups\n\nContact: [EMAIL] | [PHONE]', variables: ['EMAIL', 'PHONE'] },
]

const TYPE_META: Record<string, { icon: any; label: string; color: string; bg: string }> = {
  email: { icon: Mail, label: 'Email', color: 'text-blue-600', bg: 'bg-blue-50' },
  'follow-up': { icon: Send, label: 'Follow-Up', color: 'text-amber-600', bg: 'bg-amber-50' },
  proposal: { icon: FileText, label: 'Proposal', color: 'text-indigo-600', bg: 'bg-indigo-50' },
  'one-pager': { icon: Briefcase, label: 'One-Pager', color: 'text-emerald-600', bg: 'bg-emerald-50' },
}

export default function OutreachTemplates() {
  const [activeTab, setActiveTab] = useState('all')
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const filtered = activeTab === 'all' ? TEMPLATES : TEMPLATES.filter(t => t.type === activeTab)
  const copyToClipboard = (text: string, id: string) => { navigator.clipboard.writeText(text); setCopiedId(id); setTimeout(() => setCopiedId(null), 2000) }

  return (
    <div className="space-y-6">
      <div><h2 className="text-lg font-semibold">Outreach & Proposal Templates</h2><p className="text-sm text-muted-foreground">{TEMPLATES.length} templates for investor outreach, proposals, and one-pagers</p></div>
      <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList><TabsTrigger value="all">All ({TEMPLATES.length})</TabsTrigger><TabsTrigger value="email">Emails ({TEMPLATES.filter(t => t.type === 'email').length})</TabsTrigger><TabsTrigger value="follow-up">Follow-Ups ({TEMPLATES.filter(t => t.type === 'follow-up').length})</TabsTrigger><TabsTrigger value="proposal">Proposals ({TEMPLATES.filter(t => t.type === 'proposal').length})</TabsTrigger><TabsTrigger value="one-pager">One-Pagers ({TEMPLATES.filter(t => t.type === 'one-pager').length})</TabsTrigger></TabsList></Tabs>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filtered.map(template => { const meta = TYPE_META[template.type]; const Icon = meta.icon; const isExpanded = expandedId === template.id; return (
          <Card key={template.id} className="hover:shadow-md transition-shadow"><CardContent className="p-5 space-y-3"><div className="flex items-start justify-between"><div className="flex items-start gap-3"><div className={cn('p-2 rounded-lg shrink-0', meta.bg)}><Icon className={cn('h-5 w-5', meta.color)} /></div><div><h3 className="font-semibold text-sm">{template.title}</h3><div className="flex items-center gap-2 mt-1"><Badge variant="secondary" className="text-[10px]">{meta.label}</Badge>{template.sector && <Badge variant="outline" className="text-[10px]">{template.sector}</Badge>}</div></div></div></div><div className={cn('bg-muted/30 rounded-lg p-3 text-xs font-mono whitespace-pre-wrap max-h-32 overflow-hidden', !isExpanded && 'relative')}>{template.content.substring(0, 200)}...{!isExpanded && <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-muted/30 to-transparent" />}</div>{template.variables && template.variables.length > 0 && <div className="flex flex-wrap gap-1.5">{template.variables.map((v, i) => (<Badge key={i} variant="outline" className="text-[10px] font-mono">[{v}]</Badge>))}</div>}<div className="flex gap-2"><Button variant="ghost" size="sm" className="flex-1 text-xs" onClick={() => setExpandedId(isExpanded ? null : template.id)}>{isExpanded ? <><ChevronUp className="h-3 w-3 mr-1" /> Less</> : <><ChevronDown className="h-3 w-3 mr-1" /> Preview</>}</Button><Button variant="outline" size="sm" className="text-xs" onClick={() => copyToClipboard(template.content, template.id)}>{copiedId === template.id ? <><Check className="h-3 w-3 mr-1" /> Copied!</> : <><Copy className="h-3 w-3 mr-1" /> Copy</>}</Button></div>{isExpanded && <><Separator /><div className="bg-white dark:bg-gray-950 rounded-lg p-4 text-xs font-mono whitespace-pre-wrap max-h-96 overflow-y-auto border">{template.content}</div><p className="text-[10px] text-muted-foreground text-center">Replace [VARIABLE] placeholders before sending</p></>}</CardContent></Card>
        )})}
      </div>
      <Card className="border-dashed"><CardContent className="p-5"><h3 className="font-semibold text-sm mb-2">💡 Template Usage Tips</h3><ul className="text-xs text-muted-foreground space-y-1.5"><li>• <strong>Personalize every template</strong> — Replace all [VARIABLE] placeholders</li><li>• <strong>NCNDA first</strong> — Execute confidentiality before sharing deal details</li><li>• <strong>Follow up within 48 hours</strong> — Use follow-up templates after initial contact</li><li>• <strong>Track responses</strong> — Log all outreach in your Deal Pipeline Dashboard</li><li>• <strong>Sector-specific proposals</strong> — Choose the template closest to your deal</li></ul></CardContent></Card>
    </div>
  )
}